# **1. 파이토치**
- Tensorflow와 함께 머신러닝, 딥러닝에서 가장 널리 사용되는 프레임워크
- 초기에는 Torch 라는 이름으로 Lua언어 기반으로 만들어졌으나, 파이썬 기반으로 변경한 것이 Pytorch
- 뉴욕대학교와 페이스북(메타)이 공동으로 개발하였고, 현재 가장 대중적임

In [2]:
import torch

print(torch.__version__)

2.1.0+cu118


### 1-1. 스칼라(Scalar)
- 하나의 상수를 의미

In [54]:
var1 = torch.tensor([1])

In [55]:
var1

tensor([1])

In [56]:
var2 = torch.tensor([3.1])

In [57]:
var2

tensor([3.1000])

In [58]:
# 두 스칼라의 사칙 연산
print(var1 + var2)
print(var1 - var2)
print(var1 * var2)
print(var1 / var2)

tensor([4.1000])
tensor([-2.1000])
tensor([3.1000])
tensor([0.3226])


### 1-2. 벡터(Vector)
- 상수가 두 개 이상 나열되었을 경우

In [59]:
vec1 = torch.tensor([1, 2, 3])
vec1

tensor([1, 2, 3])

In [60]:
vec2 = torch.tensor([10, 20, 30])
vec2

tensor([10, 20, 30])

In [61]:
# 두 벡터의 사칙 연산
print(vec1 + vec2)
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)

tensor([11, 22, 33])
tensor([ -9, -18, -27])
tensor([10, 40, 90])
tensor([0.1000, 0.1000, 0.1000])


In [62]:
vec3 = torch.tensor([10, 20, 30, 40])
vec3

tensor([10, 20, 30, 40])

In [63]:
# The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0
# print(vec1 + vec3)
# print(vec1 - vec3)
# print(vec1 * vec3)
# print(vec1 / vec3)

### 1-3. 행렬(Matrix)
- 2개 이상의 벡터 값을 가지고 만들어진 값으로 행과 열의 개념을 가진 숫자의 나열

In [64]:
mat1 = torch.tensor([[1, 2], [3, 4]])
print(mat1)

tensor([[1, 2],
        [3, 4]])


In [65]:
mat2 = torch.tensor([[7, 8], [9, 10]])
print(mat2)

tensor([[ 7,  8],
        [ 9, 10]])


In [66]:
mat3 = torch.tensor([[7, 8, 9], [9, 10, 11]])
print(mat3)

tensor([[ 7,  8,  9],
        [ 9, 10, 11]])


In [67]:
# print(mat1 + mat3)

In [68]:
# 두 행렬의 사칙연산
print(mat1 + mat2)
print(mat1 - mat2)
print(mat1 * mat2)
print(mat1 / mat2)

tensor([[ 8, 10],
        [12, 14]])
tensor([[-6, -6],
        [-6, -6]])
tensor([[ 7, 16],
        [27, 40]])
tensor([[0.1429, 0.2500],
        [0.3333, 0.4000]])


### 1-4. 텐서(Tensor)
- 다수의 행렬이 모이면 텐서
- 배열이나 행렬과 매우 유사한 특수 자료구조
- 파이토치는 텐서를 사용하여 모델의 입력과 출력, 모델의 매개변수들을 처리 사용

<img src = 'https://miro.medium.com/max/875/1*jRyyMAhS_NZxqyv3EoLCvg.png' width = 500>

In [69]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([10, 20, 30])

# 브로드캐스팅을 사용하여 A와 B를 덧셈
# 작은 배열이 큰 배열로 확장되어 연산을 수행했다.
print(A)
print('=======================')
print(B)
print('=======================')
print(A + B)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([10, 20, 30])
tensor([[11, 22, 33],
        [14, 25, 36]])


In [70]:
tensor1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor1)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [71]:
tensor2 = torch.tensor([[[10, 11], [12, 13]], [[14, 15], [16, 17]]])
print(tensor2)

tensor([[[10, 11],
         [12, 13]],

        [[14, 15],
         [16, 17]]])


In [72]:
print(tensor1 + tensor2)
print('==============================')
print(tensor1 - tensor2)
print('==============================')
print(tensor1 * tensor2)
print('==============================')
print(tensor1 / tensor2)

tensor([[[11, 13],
         [15, 17]],

        [[19, 21],
         [23, 25]]])
tensor([[[-9, -9],
         [-9, -9]],

        [[-9, -9],
         [-9, -9]]])
tensor([[[ 10,  22],
         [ 36,  52]],

        [[ 70,  90],
         [112, 136]]])
tensor([[[0.1000, 0.1818],
         [0.2500, 0.3077]],

        [[0.3571, 0.4000],
         [0.4375, 0.4706]]])


In [73]:
print(torch.add(tensor1, tensor2))
print('==============================')
print(torch.subtract(tensor1, tensor2))
print('==============================')
print(torch.multiply(tensor1, tensor2))
print('==============================')
print(torch.divide(tensor1, tensor2))

tensor([[[11, 13],
         [15, 17]],

        [[19, 21],
         [23, 25]]])
tensor([[[-9, -9],
         [-9, -9]],

        [[-9, -9],
         [-9, -9]]])
tensor([[[ 10,  22],
         [ 36,  52]],

        [[ 70,  90],
         [112, 136]]])
tensor([[[0.1000, 0.1818],
         [0.2500, 0.3077]],

        [[0.3571, 0.4000],
         [0.4375, 0.4706]]])


In [74]:
# tensor1에 결과를 다시 저장, 모든 사칙연산자에 _를 붙여 사용할 수 있음.
print(tensor1.add_(tensor2))

tensor([[[11, 13],
         [15, 17]],

        [[19, 21],
         [23, 25]]])


In [75]:
tensor1

tensor([[[11, 13],
         [15, 17]],

        [[19, 21],
         [23, 25]]])

# **2. 텐서의 변환**

In [76]:
data = [[1, 2], [3, 4]]
data

[[1, 2], [3, 4]]

In [77]:
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [78]:
import numpy as np

In [79]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [80]:
x_np_1 = torch.tensor(np_array)
x_np_1

tensor([[1, 2],
        [3, 4]])

In [83]:
# 인덱싱? okay
x_np_1[0, 0] = 100
print(x_np_1)

tensor([[100,   2],
        [  3,   4]])


In [87]:
# as_tensor : ndarray와 동일한 메모리 주소를 가리키는 뷰를 만듦
# from_numpy : ndarray와 동일한 메모리 주소를 가리키는 뷰를 만듦
x_np_2 = torch.as_tensor(np_array)
print(x_np_2)
x_np_2[0, 0] = 200
print(x_np_2)
print(np_array)

# 반대로도 확인!
print('===============================')
np_array[0, 0] = 500
print(x_np_2)
print(np_array)

tensor([[200,   2],
        [  3,   4]])
tensor([[200,   2],
        [  3,   4]])
[[200   2]
 [  3   4]]
tensor([[500,   2],
        [  3,   4]])
[[500   2]
 [  3   4]]


In [89]:
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[100   2]
 [  3   4]] <class 'numpy.ndarray'>


# **3. 파이토치 함수**

In [90]:
a = torch.ones(2, 3)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [91]:
b = torch.zeros(2, 3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [92]:
c = torch.full((2, 3), 10)
print(c)

tensor([[10, 10, 10],
        [10, 10, 10]])


In [93]:
d = torch.empty(2, 3)
print(d)

tensor([[-7.0018e-02,  3.1568e-41, -6.1624e-02],
        [ 3.1568e-41,         nan,  3.1568e-41]])


In [97]:
e = torch.eye(5)
print(e)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [98]:
f = torch.arange(10)
print(f)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [99]:
g = torch.rand(2, 3)
print(g)

tensor([[0.1320, 0.1489, 0.6801],
        [0.2895, 0.7038, 0.2226]])


In [101]:
# 평균이 0 이고 표준편차가 1
h = torch.randn(2, 3)
print(h)

tensor([[-0.6913,  0.2582, -0.7980],
        [ 0.7029, -0.7114, -0.5091]])


In [102]:
i = torch.arange(16).reshape(2, 2, 4)
print(i, i.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [103]:
j = i.permute((2, 0, 1)) # 2, 2, 4 -> 4, 2, 2
print(j, j.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


# **4. 텐서의 인덱싱과 슬라이싱**

In [109]:
a = torch.arange(1, 13).reshape(3, 4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [108]:
# 증강값도 실수 단위로 가능!
temp = torch.arange(1, 13, 0.5).reshape(6, 4)
print(temp)

tensor([[ 1.0000,  1.5000,  2.0000,  2.5000],
        [ 3.0000,  3.5000,  4.0000,  4.5000],
        [ 5.0000,  5.5000,  6.0000,  6.5000],
        [ 7.0000,  7.5000,  8.0000,  8.5000],
        [ 9.0000,  9.5000, 10.0000, 10.5000],
        [11.0000, 11.5000, 12.0000, 12.5000]])


In [111]:
print(a[1])

tensor([5, 6, 7, 8])


In [114]:
print(a[1, -2])

tensor(7)


In [118]:
print(a[0:2])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [119]:
print(a[:2, 2:])

tensor([[3, 4],
        [7, 8]])


# **5. 코랩의 GPU 사용**
- 코랩에서 device 변경하는 방법
  - 상단 메뉴 -> 런타임 -> 런타임 유형변경 -> 하드웨어 가속기를 GPU로 변경 -> 저장 -> 다시 시작 및 모두 실행

In [120]:
tensor = torch.rand(3, 4)
print(f'shape -> {tensor.shape}')
print(f'shape -> {tensor.dtype}')
print(f'shape -> {tensor.device}')

shape -> torch.Size([3, 4])
shape -> torch.float32
shape -> cpu


In [5]:
tensor = torch.rand(4, 3)
# 데이터의 형변환!
tensor = tensor.int()

if torch.cuda.is_available():
  print('GPU 사용 가능')
  tensor = tensor.to('cuda')

print(f'shape -> {tensor.shape}')
print(f'shape -> {tensor.dtype}')
print(f'shape -> {tensor.device}')

GPU 사용 가능
shape -> torch.Size([4, 3])
shape -> torch.int32
shape -> cuda:0


In [3]:
# gpu 사용할 수 있는지 여부
torch.cuda.is_available()

True

In [4]:
tensor = torch.rand(3, 4)
print(f'shape -> {tensor.shape}')
print(f'shape -> {tensor.dtype}')
print(f'shape -> {tensor.device}')

shape -> torch.Size([3, 4])
shape -> torch.float32
shape -> cpu
